### ISSUE TITLE
ModuleNotFoundError: No module named 'trading_spread'

### ISSUE THREAD

**Issue by jalalmzh** [cove9988/TradingGym#7]
hi 
when I run this code "python C:\Users\jalal\TradingGym\examples\dqn_agent.py" I got below error
how can I fix it?
"C:\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "C:\Users\jalal\TradingGym\examples\dqn_agent.py", line 15, in <module>
    from tgym.envs.trading_spread import SpreadTrading
  File "C:\Anaconda3\lib\site-packages\tgym\envs\__init__.py", line 1, in <module>
    from trading_spread import SpreadTrading
ModuleNotFoundError: No module named 'trading_spread'"

**Comment by windowshopr** [comment]
Delete the "tgym." from the line "from tgym.envs.trading_spread import SpreadTrading". The tgym folder doesn't have envs folder in it, the envs folder is in the main directory. You'll have to do that in any other scripts that have those lines.
