### ISSUE TITLE
ModuleNotFoundError: No module named 'trading'

### ISSUE THREAD

**Issue by smileyung** [cove9988/TradingGym#8]
Using TensorFlow backend.
Traceback (most recent call last):
  File "dqn_agent.py", line 15, in <module>
    from tgym.envs.trading_spread import SpreadTrading
  File "/home/smilewater/anaconda3/lib/python3.6/site-packages/tgym/envs/__init__.py", line 1, in <module>
    from trading import SpreadTrading
ModuleNotFoundError: No module named 'trading'

**Comment by windowshopr** [comment]
Delete the "tgym." from the line "tgym.envs.trading_spread import SpreadTrading". The tgym folder doesn't have envs folder in it, the envs folder is in the main directory. You'll have to do that in any other scripts that have those lines.
